<#
.SYNOPSIS
    Regenerates .kiro/steering/ from the canonical manifest.

.DESCRIPTION
    Uses #[[file:]] references — no content duplication.

    Safe behavior:
      - Only manages files whose names match the generated pattern (NN-<slug>.md)
        AND were previously generated by this script (detected via header marker).
      - Never deletes manually maintained or project-specific steering files.
      - Fails visibly if a canonical source listed in the manifest does not exist.
      - Idempotent: running twice produces no diff.
#>
[CmdletBinding()]
param()

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$GeneratedMarker = 'GENERATED RUNTIME COPY'

# Resolve repository root (scripts/ is one level below root)
$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$Root = Split-Path -Parent $ScriptDir
$Manifest = Join-Path $Root 'kiro/self-steering-manifest.txt'
$Target = Join-Path $Root '.kiro/steering'

# --- Preflight checks ---

if (-not (Test-Path $Manifest)) {
    Write-Error "Manifest not found: $Manifest"
    exit 1
}

if (-not (Test-Path $Target)) {
    New-Item -ItemType Directory -Path $Target -Force | Out-Null
}

# --- Parse manifest and generate files ---

$expectedFiles = @()
$errors = 0

foreach ($line in Get-Content $Manifest) {
    # Skip comments and blank lines
    if ($line -match '^\s*#' -or $line -match '^\s*$') { continue }

    # Parse: <prefix> <path> <title...>
    $parts = $line -split '\s+', 3
    if ($parts.Count -lt 3) {
        Write-Warning "Malformed manifest line: $line"
        $errors++
        continue
    }

    $prefix = $parts[0]
    $sourcePath = $parts[1]
    $title = $parts[2]

    # Derive output filename slug from the canonical filename
    $slug = [System.IO.Path]::GetFileNameWithoutExtension($sourcePath)
    $destName = "${prefix}-${slug}.md"
    $destFile = Join-Path $Target $destName

    # Verify canonical source exists
    $fullSourcePath = Join-Path $Root $sourcePath
    if (-not (Test-Path $fullSourcePath)) {
        Write-Error "Canonical source does not exist: $sourcePath"
        $errors++
        continue
    }

    # Track expected files for cleanup phase
    $expectedFiles += $destName

    # Generate the runtime steering file
    $content = @"
---
inclusion: always
---

<!-- ${GeneratedMarker} — DO NOT EDIT INDEPENDENTLY
     Canonical source: ${sourcePath}
     Regenerate with: scripts/sync-self-steering.ps1
     Any edits here will be overwritten on next sync. -->

# ${title} (Active Steering)

This file activates the ${title} rules for Kiro Web.

#[[file:${sourcePath}]]
"@

    Set-Content -Path $destFile -Value $content -Encoding UTF8 -NoNewline
    # Ensure trailing newline
    Add-Content -Path $destFile -Value ''
}

# --- Fail if any canonical source was missing ---

if ($errors -gt 0) {
    Write-Error "FAILED: $errors canonical source(s) missing. Aborting without cleanup."
    exit 1
}

# --- Cleanup obsolete generated files ---

foreach ($existing in Get-ChildItem -Path $Target -Filter '*.md' -File) {
    if ($expectedFiles -contains $existing.Name) { continue }

    # Only delete if it contains our generated marker
    $fileContent = Get-Content $existing.FullName -Raw -ErrorAction SilentlyContinue
    if ($fileContent -and $fileContent.Contains($GeneratedMarker)) {
        Write-Host "Removing obsolete generated file: $($existing.Name)"
        Remove-Item $existing.FullName -Force
    }
}

# --- Report ---

Write-Host "Self-steering synchronized: $Target/"
Get-ChildItem -Path $Target -Filter '*.md' -File | ForEach-Object { Write-Host $_.Name }
