#!/usr/bin/env bash
set -euo pipefail

# sync-self-steering.sh
#
# Regenerates .kiro/steering/ from the canonical manifest.
# Uses #[[file:]] references — no content duplication.
#
# Safe behavior:
#   - Only manages files whose names match the generated pattern (NN-<slug>.md)
#     AND were previously generated by this script (detected via header marker).
#   - Never deletes manually maintained or project-specific steering files.
#   - Fails visibly if a canonical source listed in the manifest does not exist.
#   - Idempotent: running twice produces no diff.

GENERATED_MARKER="GENERATED RUNTIME COPY"

# Resolve repository root
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
MANIFEST="${ROOT}/kiro/self-steering-manifest.txt"
TARGET="${ROOT}/.kiro/steering"

# --- Preflight checks ---

if [ ! -f "${MANIFEST}" ]; then
  echo "ERROR: Manifest not found: ${MANIFEST}" >&2
  exit 1
fi

mkdir -p "${TARGET}"

# --- Parse manifest and generate files ---

expected_files=""
errors=0

while IFS= read -r line; do
  # Skip comments and blank lines
  case "${line}" in
    "#"*|"") continue ;;
  esac

  # Parse: <prefix> <path> <title...>
  prefix="$(echo "${line}" | awk '{print $1}')"
  source_path="$(echo "${line}" | awk '{print $2}')"
  title="$(echo "${line}" | awk '{$1=""; $2=""; sub(/^[[:space:]]+/, ""); print}')"

  # Derive output filename slug from the canonical filename
  slug="$(basename "${source_path}" .md)"
  dest_name="${prefix}-${slug}.md"
  dest_file="${TARGET}/${dest_name}"

  # Verify canonical source exists
  if [ ! -f "${ROOT}/${source_path}" ]; then
    echo "ERROR: Canonical source does not exist: ${source_path}" >&2
    errors=$((errors + 1))
    continue
  fi

  # Track expected files for cleanup phase
  expected_files="${expected_files} ${dest_name}"

  # Generate the runtime steering file
  cat > "${dest_file}" <<EOF
---
inclusion: always
---

<!-- ${GENERATED_MARKER} — DO NOT EDIT INDEPENDENTLY
     Canonical source: ${source_path}
     Regenerate with: scripts/sync-self-steering.sh
     Any edits here will be overwritten on next sync. -->

# ${title} (Active Steering)

This file activates the ${title} rules for Kiro Web.

#[[file:${source_path}]]
EOF

done < "${MANIFEST}"

# --- Fail if any canonical source was missing ---

if [ "${errors}" -gt 0 ]; then
  echo "FAILED: ${errors} canonical source(s) missing. Aborting without cleanup." >&2
  exit 1
fi

# --- Cleanup obsolete generated files ---

for existing in "${TARGET}"/*.md; do
  [ -f "${existing}" ] || continue
  filename="$(basename "${existing}")"

  # Check if this file is in the expected set
  is_expected=0
  for expected in ${expected_files}; do
    if [ "${filename}" = "${expected}" ]; then
      is_expected=1
      break
    fi
  done

  if [ "${is_expected}" -eq 0 ]; then
    # Only delete if it contains our generated marker
    if grep -q "${GENERATED_MARKER}" "${existing}" 2>/dev/null; then
      echo "Removing obsolete generated file: ${filename}"
      rm -f "${existing}"
    fi
  fi
done

# --- Report ---

echo "Self-steering synchronized: ${TARGET}/"
ls -1 "${TARGET}/"
